@startuml

class ToDoListManager {
    +Gson serializer;
    +createList(String title);
}

class ToDoList {
    -String path;
    -String title;
    -ObservableList<Task> tasks;

    +addTask(String description);
    +removeTask(Task task);
    +clearAllTasks();
    +load();
    +save();
    +toString();
}

class Task {
    -String description;
    -Date dueDate;
    'Format due date as YYYY-MM-DD'
    -private boolean isComplete;

    +setCompletion(boolean complete);
    +isComplete();
    +setDescription(String description);
    +getDescription();
    +toString();
}

@enduml