@startuml

class ToDoListManager {
    +createList(String title);
    +selectList(long id);
}

class ToDoList {
    -String title;
    -LinkedList<Task> tasks;

    +addTask(String description);
    +deleteTask();
    +rename();
    +delete();
}

class Task {
    -String description;
    -Date dueDate;
    'Format due date as YYYY-MM-DD'

    -boolean isComplete;

    +setDescription(String description);
    +setDueDate(Date dueDate);
    +setComplete();
    +setIncomplete();
    +delete();
}

@enduml