@startuml

class ToDoListManager {
    +createList(String title);
}

class ToDoList {
    -String title;
    -LinkedList<Task> tasks;

    +addTask(String description);
    +deleteTask();
    +rename();
    +delete();

}

class Task {
    -String description;
    -Date dueDate;
    'Format due date as YYYY-MM-DD'

    -Date dateCreated;
    -Date dateCompleted;
    -boolean isComplete;

    +delete()
}

@enduml